### PR TITLE
Added support for python 3 using six module

### PR DESCRIPTION
**Pull request by gopivalleru**
support python3 along with python2 > 2.6.

File: actions/lib/base.py

changes:

import six
Change check.iteritems() to six.iteritems(check).

### CODE REVIEW

**Comment by blag** [comment]
This looks good! Please add a commit to bump the version to 1.0.2 in `pack.yaml` and add a changelog entry for 1.0.2 to `CHANGES.md`.

**Comment by namachieli** [comment]
lgtm, thanks for this!

**Comment by gopivalleru** [comment]
@blag bumped the version to 1.0.2 in pack.yaml and add a changelog entry for 1.0.2 to CHANGES.md

**Comment by gopivalleru** [comment]
@blag and @namachieli, Let me if you need anything else from me.

**Comment by blag** [comment]
Thanks!

**Comment by gopivalleru** [comment]
closes #21

**Pull request merged**
